feat: add node overcommit annotation consts
kubewharf/katalyst-api pull request #32
Opened 2023-08-16 08:53 UTC by WangZzzhe

#### What type of PR is this?
Features

#### What this PR does / why we need it:
add node overcommit annotation key consts for
1) record node CPU and memory overcommit ratio
the annotation value will be used to calculate node virtual capacity and allocatable in mutating webhook
2) record capacity and allocatable before overcommited

2023-08-16 09:48 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/kubewharf/katalyst-api?pullRequest=32) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/kubewharf/katalyst-api?pullRequest=32) before we can accept your contribution.<br/><hr/>**wangzhe.21** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/kubewharf/katalyst-api?pullRequest=32) it.</sub>

2023-08-21 02:40 UTC, waynepeking348 approved these changes

2023-08-23 08:15 UTC, caohe requested changes

2023-08-23 08:15 UTC, caohe commented on pkg/consts/overcommit.go
> +	NodeAnnotationCPUOvercommitRatioKey    = "katalyst.kubewharf.io/CPU_overcommit_ratio"
Maybe it would be better to use lowercase letters? For example, `katalyst.kubewharf.io/cpu_overcommit_ratio`.

2023-08-23 08:15 UTC, caohe commented on pkg/consts/overcommit.go
> +	NodeAnnotationNativeCapacityCPUKey       = "katalyst.kubewharf.io/native_capacity_CPU"
Maybe it would be better to name it `katalyst.kubewharf.io/original_capacity_cpu` or `katalyst.kubewharf.io/real_capacity_cpu`?

2023-08-23 08:29 UTC, WangZzzhe commented on pkg/consts/overcommit.go
> +	NodeAnnotationCPUOvercommitRatioKey    = "katalyst.kubewharf.io/CPU_overcommit_ratio"
Done. All 'CPU' in consts has been updated to lowercase letters.

2023-08-23 12:51 UTC, caohe approved these changes
LGTM

2023-08-24 06:35 UTC, waynepeking348 approved these changes

2023-08-24 06:36 UTC, waynepeking348 commented
@caohe this api seems lgtm for me, shall we merge this now?

2023-08-24 07:17 UTC, merged